# Lista de patrones personalizados para EntityRuler (formato Python)
patterns = [
    # Dispositivos y variantes ampliados
    # Patrones de un solo token para DISPOSITIVO
    {"label": "DISPOSITIVO", "pattern": "luces"},
    {"label": "DISPOSITIVO", "pattern": "luz"},
    {"label": "DISPOSITIVO", "pattern": "lucecitas"},
    {"label": "DISPOSITIVO", "pattern": "foco"},
    {"label": "DISPOSITIVO", "pattern": "focos"},
    {"label": "DISPOSITIVO", "pattern": "bombilla"},
    {"label": "DISPOSITIVO", "pattern": "bombillas"},
    {"label": "DISPOSITIVO", "pattern": "lampara"},
    {"label": "DISPOSITIVO", "pattern": "lámpara"},
    {"label": "DISPOSITIVO", "pattern": "iluminación"},
    {"label": "DISPOSITIVO", "pattern": "iluminacion"},
    {"label": "DISPOSITIVO", "pattern": "tele"},
    {"label": "DISPOSITIVO", "pattern": "televisor"},
    {"label": "DISPOSITIVO", "pattern": "tv"},
    {"label": "DISPOSITIVO", "pattern": "pantalla"},
    {"label": "DISPOSITIVO", "pattern": "pantallón"},
    {"label": "DISPOSITIVO", "pattern": "monitor"},
    {"label": "DISPOSITIVO", "pattern": "smart tv"},
    {"label": "DISPOSITIVO", "pattern": "puerta"},
    {"label": "DISPOSITIVO", "pattern": "ventana"},
    {"label": "DISPOSITIVO", "pattern": "portón"},
    {"label": "DISPOSITIVO", "pattern": "porton"},
    {"label": "DISPOSITIVO", "pattern": "persiana"},
    {"label": "DISPOSITIVO", "pattern": "puertita"},
    {"label": "DISPOSITIVO", "pattern": "ventanita"},
    {"label": "DISPOSITIVO", "pattern": "impresora"},
    {"label": "DISPOSITIVO", "pattern": "impresora 3d"},
    {"label": "DISPOSITIVO", "pattern": "printer"},
    {"label": "DISPOSITIVO", "pattern": "plotter"},
    {"label": "DISPOSITIVO", "pattern": "cámara"},
    {"label": "DISPOSITIVO", "pattern": "camara"},
    {"label": "DISPOSITIVO", "pattern": "webcam"},
    {"label": "DISPOSITIVO", "pattern": "camarita"},
    {"label": "DISPOSITIVO", "pattern": "auto"},
    {"label": "DISPOSITIVO", "pattern": "vehículo"},
    {"label": "DISPOSITIVO", "pattern": "vehiculo"},
    {"label": "DISPOSITIVO", "pattern": "coche"},
    {"label": "DISPOSITIVO", "pattern": "carro"},
    {"label": "DISPOSITIVO", "pattern": "automóvil"},
    {"label": "DISPOSITIVO", "pattern": "automovil"},
    {"label": "DISPOSITIVO", "pattern": "música"},
    {"label": "DISPOSITIVO", "pattern": "musica"},
    {"label": "DISPOSITIVO", "pattern": "radio"},
    {"label": "DISPOSITIVO", "pattern": "parlante"},
    {"label": "DISPOSITIVO", "pattern": "altavoz"},
    {"label": "DISPOSITIVO", "pattern": "bocina"},
    {"label": "DISPOSITIVO", "pattern": "speaker"},
    {"label": "DISPOSITIVO", "pattern": "notas"},
    {"label": "DISPOSITIVO", "pattern": "nota"},
    {"label": "DISPOSITIVO", "pattern": "recordatorio"},
    {"label": "DISPOSITIVO", "pattern": "apunte"},
    {"label": "DISPOSITIVO", "pattern": "memo"},
    {"label": "DISPOSITIVO", "pattern": "clima"},
    {"label": "DISPOSITIVO", "pattern": "tiempo"},
    {"label": "DISPOSITIVO", "pattern": "temperatura"},
    {"label": "DISPOSITIVO", "pattern": "ambiente"},
    {"label": "DISPOSITIVO", "pattern": "noticias"},
    {"label": "DISPOSITIVO", "pattern": "news"},
    {"label": "DISPOSITIVO", "pattern": "informativo"},
    {"label": "DISPOSITIVO", "pattern": "boletín"},
    {"label": "DISPOSITIVO", "pattern": "boletin"},
    {"label": "DISPOSITIVO", "pattern": "contactos"},
    {"label": "DISPOSITIVO", "pattern": "contacto"},
    {"label": "DISPOSITIVO", "pattern": "agenda"},
    {"label": "DISPOSITIVO", "pattern": "teléfonos"},
    {"label": "DISPOSITIVO", "pattern": "telefonos"},
    {"label": "DISPOSITIVO", "pattern": "modelo"},
    {"label": "DISPOSITIVO", "pattern": "modelo 3d"},
    {"label": "DISPOSITIVO", "pattern": "maqueta"},
    {"label": "DISPOSITIVO", "pattern": "prototipo"},
    {"label": "DISPOSITIVO", "pattern": "sistema de seguridad"},
    {"label": "DISPOSITIVO", "pattern": "alarma"},
    {"label": "DISPOSITIVO", "pattern": "sensor"},
    {"label": "DISPOSITIVO", "pattern": "alarma antirrobo"},
    {"label": "DISPOSITIVO", "pattern": "ventilador"},
    {"label": "DISPOSITIVO", "pattern": "calefacción"},
    {"label": "DISPOSITIVO", "pattern": "calefaccion"},
    {"label": "DISPOSITIVO", "pattern": "aire"},
    {"label": "DISPOSITIVO", "pattern": "ac"},
    {"label": "DISPOSITIVO", "pattern": "aire acondicionado"},
    {"label": "DISPOSITIVO", "pattern": "brillo"},
    {"label": "DISPOSITIVO", "pattern": "pantalla"},
    {"label": "DISPOSITIVO", "pattern": "contraste"},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": {"IN": [
        "tele", "televisor", "tv", "pantalla", "pantallón", "monitor", "smart tv"
    ]}}]},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": {"IN": [
        "puerta", "ventana", "portón", "porton", "persiana", "puertita", "ventanita"
    ]}}]},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": {"IN": [
        "impresora", "impresora 3d", "printer", "plotter"
    ]}}]},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": {"IN": [
        "cámara", "camara", "webcam", "camarita"
    ]}}]},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": {"IN": [
        "auto", "vehículo", "vehiculo", "coche", "carro", "automóvil", "automovil"
    ]}}]},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": {"IN": [
        "música", "musica", "radio", "parlante", "altavoz", "bocina", "speaker"
    ]}}]},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": {"IN": [
        "notas", "nota", "recordatorio", "apunte", "memo"
    ]}}]},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": {"IN": [
        "clima", "tiempo", "temperatura", "ambiente"
    ]}}]},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": {"IN": [
        "noticias", "news", "informativo", "boletín", "boletin"
    ]}}]},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": {"IN": [
        "contactos", "contacto", "agenda", "teléfonos", "telefonos"
    ]}}]},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": {"IN": [
        "modelo", "modelo 3d", "maqueta", "prototipo"
    ]}}]},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": {"IN": [
        "sistema de seguridad", "alarma", "sensor", "alarma antirrobo"
    ]}}]},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": {"IN": [
        "ventilador", "calefacción", "calefaccion", "aire", "ac", "aire acondicionado"
    ]}}]},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": {"IN": [
        "brillo", "pantalla", "contraste"
    ]}}]},

    # Comandos e intenciones ampliados
    # Patrones de un solo token para COMANDO (solo verbo/intención)
    {"label": "COMANDO", "pattern": "enciende"},
    {"label": "COMANDO", "pattern": "prende"},
    {"label": "COMANDO", "pattern": "activa"},
    {"label": "COMANDO", "pattern": "enciéndeme"},
    {"label": "COMANDO", "pattern": "prendé"},
    {"label": "COMANDO", "pattern": "actívalo"},
    {"label": "COMANDO", "pattern": "activalo"},
    {"label": "COMANDO", "pattern": "apaga"},
    {"label": "COMANDO", "pattern": "apagá"},
    {"label": "COMANDO", "pattern": "desactiva"},
    {"label": "COMANDO", "pattern": "apágame"},
    {"label": "COMANDO", "pattern": "desactívalo"},
    {"label": "COMANDO", "pattern": "desactivalo"},
    {"label": "COMANDO", "pattern": "sube"},
    {"label": "COMANDO", "pattern": "subí"},
    {"label": "COMANDO", "pattern": "aumenta"},
    {"label": "COMANDO", "pattern": "incrementa"},
    {"label": "COMANDO", "pattern": "alza"},
    {"label": "COMANDO", "pattern": "baja"},
    {"label": "COMANDO", "pattern": "bajá"},
    {"label": "COMANDO", "pattern": "reduce"},
    {"label": "COMANDO", "pattern": "disminuye"},
    {"label": "COMANDO", "pattern": "disminuí"},
    {"label": "COMANDO", "pattern": "abre"},
    {"label": "COMANDO", "pattern": "abrí"},
    {"label": "COMANDO", "pattern": "ábreme"},
    {"label": "COMANDO", "pattern": "cierra"},
    {"label": "COMANDO", "pattern": "cerrá"},
    {"label": "COMANDO", "pattern": "ciérrame"},
    {"label": "COMANDO", "pattern": "pon"},
    {"label": "COMANDO", "pattern": "poné"},
    {"label": "COMANDO", "pattern": "reproduce"},
    {"label": "COMANDO", "pattern": "coloca"},
    {"label": "COMANDO", "pattern": "pausa"},
    {"label": "COMANDO", "pattern": "detén"},
    {"label": "COMANDO", "pattern": "pará"},
    {"label": "COMANDO", "pattern": "deten"},
    {"label": "COMANDO", "pattern": "reserva"},
    {"label": "COMANDO", "pattern": "reservá"},
    {"label": "COMANDO", "pattern": "aparta"},
    {"label": "COMANDO", "pattern": "crea"},
    {"label": "COMANDO", "pattern": "creá"},
    {"label": "COMANDO", "pattern": "agrega"},
    {"label": "COMANDO", "pattern": "anota"},
    {"label": "COMANDO", "pattern": "genera"},
    {"label": "COMANDO", "pattern": [{"LOWER": "qué"}, {"LOWER": {"IN": ["clima", "tiempo", "temperatura"]}}, {"LOWER": "hace"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "busca"}, {"LOWER": {"IN": ["noticias", "news"]}}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "llama"}, {"LOWER": "a"}, {"ENT_TYPE": "PERSON"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["imprime", "print"]}}, {"LOWER": {"IN": ["modelo", "maqueta"]}}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["analiza", "compara"]}}, {"LOWER": {"IN": ["modelo", "maqueta"]}}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["guarda", "salva"]}}, {"LOWER": {"IN": ["nota", "recordatorio"]}}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "activa"}, {"LOWER": "modo"}, {"LOWER": "interrumpir"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["haz", "hacé"]}}, {"LOWER": "chequeo"}, {"LOWER": "médico"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "avísame"}, {"LOWER": "si"}, {"LOWER": "hay"}, {"LOWER": "consumos"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["pon", "poné"]}}, {"LOWER": "alarma"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["enciende", "prende"]}}, {"LOWER": "el"}, {"LOWER": "ventilador"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["sube", "baja"]}}, {"LOWER": "la"}, {"LOWER": "temperatura"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["enciende", "apaga"]}}, {"LOWER": "la"}, {"LOWER": "calefacción"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["sube", "baja"]}}, {"LOWER": "el"}, {"LOWER": "brillo"}]},

    # Comandos e intenciones (más variantes y flexibilidad)
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["enciende", "prende"]}}, {"LOWER": {"IN": ["la", "las"]}}, {"LOWER": {"IN": ["luz", "luces"]}}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["apaga", "apagá"]}}, {"LOWER": {"IN": ["la", "las"]}}, {"LOWER": {"IN": ["tele", "televisor", "luz", "luces"]}}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["sube", "subí"]}}, {"LOWER": "el"}, {"LOWER": "volumen"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["baja", "bajá"]}}, {"LOWER": {"IN": ["la", "el"]}}, {"LOWER": {"IN": ["música", "volumen"]}}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["abre", "abrí"]}}, {"LOWER": "la"}, {"LOWER": "puerta"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["pon", "poné"]}}, {"LOWER": "música"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["reserva", "reservá"]}}, {"LOWER": "auto"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["crea", "creá"]}}, {"LOWER": "nota"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "qué"}, {"LOWER": "clima"}, {"LOWER": "hace"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "busca"}, {"LOWER": "noticias"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "llama"}, {"LOWER": "a"}, {"ENT_TYPE": "PERSON"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "imprime"}, {"LOWER": "modelo"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "analiza"}, {"LOWER": "modelo"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "guarda"}, {"LOWER": "nota"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "activa"}, {"LOWER": "modo"}, {"LOWER": "interrumpir"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["haz", "hacé"]}}, {"LOWER": "chequeo"}, {"LOWER": "médico"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "avísame"}, {"LOWER": "si"}, {"LOWER": "hay"}, {"LOWER": "consumos"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["pon", "poné"]}}, {"LOWER": "alarma"}]},
]
