patterns = [
                    # Comandos en subjuntivo y variantes (para preguntas indirectas y sugerencias)
                    {"label": "COMANDO", "pattern": "apague"},
                    {"label": "COMANDO", "pattern": "encienda"},
                    {"label": "COMANDO", "pattern": "abra"},
                    {"label": "COMANDO", "pattern": "cierre"},
                    {"label": "COMANDO", "pattern": "ponga"},
                    {"label": "COMANDO", "pattern": "suba"},
                    {"label": "COMANDO", "pattern": "baje"},
                    {"label": "COMANDO", "pattern": "quite"},
                    {"label": "COMANDO", "pattern": "elimine"},
                    {"label": "COMANDO", "pattern": "borre"},
                    {"label": "COMANDO", "pattern": "detenga"},
                    {"label": "COMANDO", "pattern": "pare"},
                # Comandos en infinitivo (para preguntas y modales)
                {"label": "COMANDO", "pattern": "encender"},
                {"label": "COMANDO", "pattern": "apagar"},
                {"label": "COMANDO", "pattern": "subir"},
                {"label": "COMANDO", "pattern": "bajar"},
                {"label": "COMANDO", "pattern": "abrir"},
                {"label": "COMANDO", "pattern": "cerrar"},
                {"label": "COMANDO", "pattern": "configurar"},
                {"label": "COMANDO", "pattern": "ajustar"},
                {"label": "COMANDO", "pattern": "programar"},
                {"label": "COMANDO", "pattern": "despertar"},
                {"label": "COMANDO", "pattern": "desactivar"},
                {"label": "COMANDO", "pattern": "activar"},
                {"label": "COMANDO", "pattern": "reiniciar"},
                {"label": "COMANDO", "pattern": "resetear"},
                {"label": "COMANDO", "pattern": "actualizar"},
                {"label": "COMANDO", "pattern": "sincronizar"},
                {"label": "COMANDO", "pattern": "buscar"},
                {"label": "COMANDO", "pattern": "mostrar"},
                {"label": "COMANDO", "pattern": "ocultar"},
                {"label": "COMANDO", "pattern": "silenciar"},
                {"label": "COMANDO", "pattern": "desbloquear"},
                {"label": "COMANDO", "pattern": "bloquear"},
                {"label": "COMANDO", "pattern": "llamar"},
                {"label": "COMANDO", "pattern": "enviar"},
                {"label": "COMANDO", "pattern": "mandar"},
                {"label": "COMANDO", "pattern": "responder"},
                {"label": "COMANDO", "pattern": "leer"},
                {"label": "COMANDO", "pattern": "escribir"},
                {"label": "COMANDO", "pattern": "anotar"},
                {"label": "COMANDO", "pattern": "agregar"},
                {"label": "COMANDO", "pattern": "eliminar"},
                {"label": "COMANDO", "pattern": "borrar"},
                {"label": "COMANDO", "pattern": "crear"},
                {"label": "COMANDO", "pattern": "generar"},
                {"label": "COMANDO", "pattern": "descargar"},
                {"label": "COMANDO", "pattern": "compartir"},
                # Modales comunes (puedes, quieres, podrías, etc.)
                {"label": "COMANDO", "pattern": "puedes"},
                {"label": "COMANDO", "pattern": "quieres"},
                {"label": "COMANDO", "pattern": "podrías"},
                {"label": "COMANDO", "pattern": "podrias"},
                {"label": "COMANDO", "pattern": "querrías"},
                {"label": "COMANDO", "pattern": "querrias"},
            # Comandos en imperativo negativo (no apagues, no pongas, etc)
            {"label": "COMANDO", "pattern": "apagues"},
            {"label": "COMANDO", "pattern": "pongas"},
            {"label": "COMANDO", "pattern": "abras"},
            {"label": "COMANDO", "pattern": "cierres"},
            {"label": "COMANDO", "pattern": "subas"},
            {"label": "COMANDO", "pattern": "bajes"},
            {"label": "COMANDO", "pattern": "enciendas"},
            {"label": "COMANDO", "pattern": "prendas"},
            {"label": "COMANDO", "pattern": "desactives"},
            {"label": "COMANDO", "pattern": "actives"},
            {"label": "COMANDO", "pattern": "quites"},
            {"label": "COMANDO", "pattern": "elimines"},
            {"label": "COMANDO", "pattern": "borres"},
            {"label": "COMANDO", "pattern": "detengas"},
            {"label": "COMANDO", "pattern": "pares"},
            {"label": "COMANDO", "pattern": "detengas"},
            {"label": "COMANDO", "pattern": "responda"},
            {"label": "COMANDO", "pattern": "responda"},
        {"label": "MODO", "pattern": "modo"},
    # Hogar inteligente
    {"label": "DISPOSITIVO", "pattern": "calefactor"},
    {"label": "DISPOSITIVO", "pattern": "estufa"},
    {"label": "DISPOSITIVO", "pattern": "ventilador"},
    {"label": "DISPOSITIVO", "pattern": "aire acondicionado"},
    {"label": "DISPOSITIVO", "pattern": "termostato"},
    {"label": "DISPOSITIVO", "pattern": "enchufe"},
    {"label": "DISPOSITIVO", "pattern": "enchufes"},
    {"label": "DISPOSITIVO", "pattern": "cortina"},
    {"label": "DISPOSITIVO", "pattern": "cortinas"},
    {"label": "DISPOSITIVO", "pattern": "alarma"},
    {"label": "DISPOSITIVO", "pattern": "sensor"},
    {"label": "DISPOSITIVO", "pattern": "timber"},
    {"label": "DISPOSITIVO", "pattern": "portero"},
    {"label": "DISPOSITIVO", "pattern": "cerradura"},
    {"label": "DISPOSITIVO", "pattern": "cerraduras"},
    {"label": "DISPOSITIVO", "pattern": "camara de seguridad"},
    {"label": "DISPOSITIVO", "pattern": "robot aspirador"},
    {"label": "DISPOSITIVO", "pattern": "aspiradora"},
    {"label": "DISPOSITIVO", "pattern": "lavadora"},
    {"label": "DISPOSITIVO", "pattern": "secadora"},
    {"label": "DISPOSITIVO", "pattern": "microondas"},
    {"label": "DISPOSITIVO", "pattern": "horno"},
    {"label": "DISPOSITIVO", "pattern": "cafetera"},
    {"label": "DISPOSITIVO", "pattern": "tostadora"},
    {"label": "DISPOSITIVO", "pattern": "heladera"},
    {"label": "DISPOSITIVO", "pattern": "refrigerador"},
    {"label": "DISPOSITIVO", "pattern": "freezer"},
    {"label": "DISPOSITIVO", "pattern": "congelador"},
    {"label": "DISPOSITIVO", "pattern": "lavavajillas"},
    {"label": "DISPOSITIVO", "pattern": "plato"},
    {"label": "DISPOSITIVO", "pattern": "platos"},
    {"label": "DISPOSITIVO", "pattern": "cocina"},
    {"label": "DISPOSITIVO", "pattern": "fuego"},
    {"label": "DISPOSITIVO", "pattern": "llama"},
    {"label": "DISPOSITIVO", "pattern": "extractor"},
    {"label": "DISPOSITIVO", "pattern": "campana"},
    {"label": "DISPOSITIVO", "pattern": "despertador"},
    {"label": "DISPOSITIVO", "pattern": "persianas"},
    {"label": "DISPOSITIVO", "pattern": "garaje"},
    {"label": "DISPOSITIVO", "pattern": "portón de garage"},
    {"label": "DISPOSITIVO", "pattern": "baño"},
    {"label": "DISPOSITIVO", "pattern": "ducha"},
    {"label": "DISPOSITIVO", "pattern": "caldera"},
    {"label": "DISPOSITIVO", "pattern": "bomba de agua"},
    {"label": "DISPOSITIVO", "pattern": "cisterna"},
    # Multimedia y oficina
    {"label": "DISPOSITIVO", "pattern": "proyector"},
    {"label": "DISPOSITIVO", "pattern": "altavoces"},
    {"label": "DISPOSITIVO", "pattern": "bocinas"},
    {"label": "DISPOSITIVO", "pattern": "auriculares"},
    {"label": "DISPOSITIVO", "pattern": "teclado"},
    {"label": "DISPOSITIVO", "pattern": "mouse"},
    {"label": "DISPOSITIVO", "pattern": "ratón"},
    {"label": "DISPOSITIVO", "pattern": "impresora láser"},
    {"label": "DISPOSITIVO", "pattern": "scanner"},
    {"label": "DISPOSITIVO", "pattern": "escáner"},
    {"label": "DISPOSITIVO", "pattern": "fax"},
    {"label": "DISPOSITIVO", "pattern": "router"},
    {"label": "DISPOSITIVO", "pattern": "modem"},
    {"label": "DISPOSITIVO", "pattern": "switch"},
    {"label": "DISPOSITIVO", "pattern": "servidor"},
    {"label": "DISPOSITIVO", "pattern": "notebook"},
    {"label": "DISPOSITIVO", "pattern": "laptop"},
    {"label": "DISPOSITIVO", "pattern": "tablet"},
    {"label": "DISPOSITIVO", "pattern": "celular"},
    {"label": "DISPOSITIVO", "pattern": "móvil"},
    {"label": "DISPOSITIVO", "pattern": "telefono"},
    {"label": "DISPOSITIVO", "pattern": "teléfono"},
    {"label": "DISPOSITIVO", "pattern": "smartphone"},
    {"label": "DISPOSITIVO", "pattern": "pc"},
    {"label": "DISPOSITIVO", "pattern": "computadora"},
    {"label": "DISPOSITIVO", "pattern": "ordenador"},
    {"label": "DISPOSITIVO", "pattern": "escritorio"},
    {"label": "DISPOSITIVO", "pattern": "monitor secundario"},
    {"label": "DISPOSITIVO", "pattern": "pantalla secundaria"},
    # Comandos adicionales
    {"label": "COMANDO", "pattern": "enciende"},
    {"label": "COMANDO", "pattern": "apaga"},
    {"label": "COMANDO", "pattern": "sube"},
    {"label": "COMANDO", "pattern": "baja"},
    {"label": "COMANDO", "pattern": "abre"},
    {"label": "COMANDO", "pattern": "cierra"},
    {"label": "COMANDO", "pattern": "configura"},
    {"label": "COMANDO", "pattern": "ajusta"},
    {"label": "COMANDO", "pattern": "programa"},
    {"label": "COMANDO", "pattern": "despierta"},
    {"label": "COMANDO", "pattern": "desactiva"},
    {"label": "COMANDO", "pattern": "activa"},
    {"label": "COMANDO", "pattern": "reinicia"},
    {"label": "COMANDO", "pattern": "resetea"},
    {"label": "COMANDO", "pattern": "actualiza"},
    {"label": "COMANDO", "pattern": "sincroniza"},
    {"label": "COMANDO", "pattern": "busca"},
    {"label": "COMANDO", "pattern": "muestra"},
    {"label": "COMANDO", "pattern": "oculta"},
    {"label": "COMANDO", "pattern": "silencia"},
    {"label": "COMANDO", "pattern": "desbloquea"},
    {"label": "COMANDO", "pattern": "bloquea"},
    {"label": "COMANDO", "pattern": "llama"},
    {"label": "COMANDO", "pattern": "envía"},
    {"label": "COMANDO", "pattern": "manda"},
    {"label": "COMANDO", "pattern": "responde"},
    {"label": "COMANDO", "pattern": "lee"},
    {"label": "COMANDO", "pattern": "escribe"},
    {"label": "COMANDO", "pattern": "anota"},
    {"label": "COMANDO", "pattern": "agrega"},
    {"label": "COMANDO", "pattern": "elimina"},
    {"label": "COMANDO", "pattern": "borra"},
    {"label": "COMANDO", "pattern": "crea"},
    {"label": "COMANDO", "pattern": "genera"},
    {"label": "COMANDO", "pattern": "descarga"},
    {"label": "COMANDO", "pattern": "sube archivo"},
    {"label": "COMANDO", "pattern": "descarga archivo"},
    {"label": "COMANDO", "pattern": "comparte"},
    {"label": "COMANDO", "pattern": "sincroniza"},
    {"label": "COMANDO", "pattern": "apaga todo"},
    {"label": "COMANDO", "pattern": "enciende todo"},
    # Dispositivos y variantes ampliados
    # Patrones de un solo token para DISPOSITIVO
    {"label": "DISPOSITIVO", "pattern": "luces"},
    {"label": "DISPOSITIVO", "pattern": "luz"},
    {"label": "DISPOSITIVO", "pattern": "lucecitas"},
    {"label": "DISPOSITIVO", "pattern": "foco"},
    {"label": "DISPOSITIVO", "pattern": "focos"},
    {"label": "DISPOSITIVO", "pattern": "bombilla"},
    {"label": "DISPOSITIVO", "pattern": "bombillas"},
    {"label": "DISPOSITIVO", "pattern": "lampara"},
    {"label": "DISPOSITIVO", "pattern": "lámpara"},
    {"label": "DISPOSITIVO", "pattern": "iluminación"},
    {"label": "DISPOSITIVO", "pattern": "iluminacion"},
    {"label": "DISPOSITIVO", "pattern": "tele"},
    {"label": "DISPOSITIVO", "pattern": "televisor"},
    {"label": "DISPOSITIVO", "pattern": "tv"},
    {"label": "DISPOSITIVO", "pattern": "pantalla"},
    {"label": "DISPOSITIVO", "pattern": "pantallón"},
    {"label": "DISPOSITIVO", "pattern": "monitor"},
    {"label": "DISPOSITIVO", "pattern": "smart tv"},
    {"label": "DISPOSITIVO", "pattern": "puerta"},
    {"label": "DISPOSITIVO", "pattern": "ventana"},
    {"label": "DISPOSITIVO", "pattern": "portón"},
    {"label": "DISPOSITIVO", "pattern": "porton"},
    {"label": "DISPOSITIVO", "pattern": "persiana"},
    {"label": "DISPOSITIVO", "pattern": "puertita"},
    {"label": "DISPOSITIVO", "pattern": "ventanita"},
    {"label": "DISPOSITIVO", "pattern": "impresora"},
    {"label": "DISPOSITIVO", "pattern": "impresora 3d"},
    {"label": "DISPOSITIVO", "pattern": "printer"},
    {"label": "DISPOSITIVO", "pattern": "plotter"},
    {"label": "DISPOSITIVO", "pattern": "cámara"},
    {"label": "DISPOSITIVO", "pattern": "camara"},
    {"label": "DISPOSITIVO", "pattern": "webcam"},
    {"label": "DISPOSITIVO", "pattern": "camarita"},
    {"label": "DISPOSITIVO", "pattern": "auto"},
    {"label": "DISPOSITIVO", "pattern": "vehículo"},
    {"label": "DISPOSITIVO", "pattern": "vehiculo"},
    {"label": "DISPOSITIVO", "pattern": "coche"},
    {"label": "DISPOSITIVO", "pattern": "carro"},
    {"label": "DISPOSITIVO", "pattern": "automóvil"},
    {"label": "DISPOSITIVO", "pattern": "automovil"},
    {"label": "DISPOSITIVO", "pattern": "música"},
    {"label": "DISPOSITIVO", "pattern": "musica"},
    {"label": "DISPOSITIVO", "pattern": "radio"},
    {"label": "DISPOSITIVO", "pattern": "parlante"},
    {"label": "DISPOSITIVO", "pattern": "altavoz"},
    {"label": "DISPOSITIVO", "pattern": "bocina"},
    {"label": "DISPOSITIVO", "pattern": "speaker"},
    {"label": "DISPOSITIVO", "pattern": "notas"},
    {"label": "DISPOSITIVO", "pattern": "nota"},
    {"label": "DISPOSITIVO", "pattern": "recordatorio"},
    {"label": "DISPOSITIVO", "pattern": "apunte"},
    {"label": "DISPOSITIVO", "pattern": "memo"},
    {"label": "DISPOSITIVO", "pattern": "clima"},
    {"label": "DISPOSITIVO", "pattern": "tiempo"},
    {"label": "DISPOSITIVO", "pattern": "temperatura"},
    {"label": "DISPOSITIVO", "pattern": "ambiente"},
    {"label": "DISPOSITIVO", "pattern": "noticias"},
    {"label": "DISPOSITIVO", "pattern": "news"},
    {"label": "DISPOSITIVO", "pattern": "informativo"},
    {"label": "DISPOSITIVO", "pattern": "boletín"},
    {"label": "DISPOSITIVO", "pattern": "boletin"},
    {"label": "DISPOSITIVO", "pattern": "contactos"},
    {"label": "DISPOSITIVO", "pattern": "contacto"},
    {"label": "DISPOSITIVO", "pattern": "agenda"},
    {"label": "DISPOSITIVO", "pattern": "teléfonos"},
    {"label": "DISPOSITIVO", "pattern": "telefonos"},
    {"label": "DISPOSITIVO", "pattern": "modelo"},
    {"label": "DISPOSITIVO", "pattern": "modelo 3d"},
    {"label": "DISPOSITIVO", "pattern": "maqueta"},
    {"label": "DISPOSITIVO", "pattern": "prototipo"},
    {"label": "DISPOSITIVO", "pattern": "sistema de seguridad"},
    {"label": "DISPOSITIVO", "pattern": "alarma"},
    {"label": "DISPOSITIVO", "pattern": "sensor"},
    {"label": "DISPOSITIVO", "pattern": "alarma antirrobo"},
    {"label": "DISPOSITIVO", "pattern": "ventilador"},
    {"label": "DISPOSITIVO", "pattern": "calefacción"},
    {"label": "DISPOSITIVO", "pattern": "calefaccion"},
    {"label": "DISPOSITIVO", "pattern": "aire"},
    {"label": "DISPOSITIVO", "pattern": "ac"},
    {"label": "DISPOSITIVO", "pattern": "aire acondicionado"},
    {"label": "DISPOSITIVO", "pattern": "brillo"},
    {"label": "DISPOSITIVO", "pattern": "pantalla"},
    {"label": "DISPOSITIVO", "pattern": "contraste"},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": {"IN": [
        "tele", "televisor", "tv", "pantalla", "pantallón", "monitor", "smart tv"
    ]}}]},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": {"IN": [
        "puerta", "ventana", "portón", "porton", "persiana", "puertita", "ventanita"
    ]}}]},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": {"IN": [
        "impresora", "impresora 3d", "printer", "plotter"
    ]}}]},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": {"IN": [
        "cámara", "camara", "webcam", "camarita"
    ]}}]},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": {"IN": [
        "auto", "vehículo", "vehiculo", "coche", "carro", "automóvil", "automovil"
    ]}}]},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": {"IN": [
        "música", "musica", "radio", "parlante", "altavoz", "bocina", "speaker"
    ]}}]},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": {"IN": [
        "notas", "nota", "recordatorio", "apunte", "memo"
    ]}}]},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": {"IN": [
        "clima", "tiempo", "temperatura", "ambiente"
    ]}}]},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": {"IN": [
        "noticias", "news", "informativo", "boletín", "boletin"
    ]}}]},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": {"IN": [
        "contactos", "contacto", "agenda", "teléfonos", "telefonos"
    ]}}]},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": {"IN": [
        "modelo", "modelo 3d", "maqueta", "prototipo"
    ]}}]},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": {"IN": [
        "sistema de seguridad", "alarma", "sensor", "alarma antirrobo"
    ]}}]},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": {"IN": [
        "ventilador", "calefacción", "calefaccion", "aire", "ac", "aire acondicionado"
    ]}}]},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": {"IN": [
        "brillo", "pantalla", "contraste"
    ]}}]},

    # Comandos e intenciones ampliados
    # Patrones de un solo token para COMANDO (solo verbo/intención)
    {"label": "COMANDO", "pattern": "enciende"},
    {"label": "COMANDO", "pattern": "prende"},
    {"label": "COMANDO", "pattern": "activa"},
    {"label": "COMANDO", "pattern": "enciéndeme"},
    {"label": "COMANDO", "pattern": "prendé"},
    {"label": "COMANDO", "pattern": "actívalo"},
    {"label": "COMANDO", "pattern": "activalo"},
    {"label": "COMANDO", "pattern": "apaga"},
    {"label": "COMANDO", "pattern": "apagá"},
    {"label": "COMANDO", "pattern": "desactiva"},
    {"label": "COMANDO", "pattern": "apágame"},
    {"label": "COMANDO", "pattern": "desactívalo"},
    {"label": "COMANDO", "pattern": "desactivalo"},
    {"label": "COMANDO", "pattern": "sube"},
    {"label": "COMANDO", "pattern": "subí"},
    {"label": "COMANDO", "pattern": "aumenta"},
    {"label": "COMANDO", "pattern": "incrementa"},
    {"label": "COMANDO", "pattern": "alza"},
    {"label": "COMANDO", "pattern": "baja"},
    {"label": "COMANDO", "pattern": "bajá"},
    {"label": "COMANDO", "pattern": "reduce"},
    {"label": "COMANDO", "pattern": "disminuye"},
    {"label": "COMANDO", "pattern": "disminuí"},
    {"label": "COMANDO", "pattern": "abre"},
    {"label": "COMANDO", "pattern": "abrí"},
    {"label": "COMANDO", "pattern": "ábreme"},
    {"label": "COMANDO", "pattern": "cierra"},
    {"label": "COMANDO", "pattern": "cerrá"},
    {"label": "COMANDO", "pattern": "ciérrame"},
    {"label": "COMANDO", "pattern": "pon"},
    {"label": "COMANDO", "pattern": "poné"},
    {"label": "COMANDO", "pattern": "reproduce"},
    {"label": "COMANDO", "pattern": "coloca"},
    {"label": "COMANDO", "pattern": "pausa"},
    {"label": "COMANDO", "pattern": "detén"},
    {"label": "COMANDO", "pattern": "pará"},
    {"label": "COMANDO", "pattern": "deten"},
    {"label": "COMANDO", "pattern": "reserva"},
    {"label": "COMANDO", "pattern": "reservá"},
    {"label": "COMANDO", "pattern": "aparta"},
    {"label": "COMANDO", "pattern": "crea"},
    {"label": "COMANDO", "pattern": "creá"},
    {"label": "COMANDO", "pattern": "agrega"},
    {"label": "COMANDO", "pattern": "anota"},
    {"label": "COMANDO", "pattern": "genera"},
    {"label": "COMANDO", "pattern": [{"LOWER": "qué"}, {"LOWER": {"IN": ["clima", "tiempo", "temperatura"]}}, {"LOWER": "hace"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "busca"}, {"LOWER": {"IN": ["noticias", "news"]}}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "llama"}, {"LOWER": "a"}, {"ENT_TYPE": "PERSON"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["imprime", "print"]}}, {"LOWER": {"IN": ["modelo", "maqueta"]}}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["analiza", "compara"]}}, {"LOWER": {"IN": ["modelo", "maqueta"]}}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["guarda", "salva"]}}, {"LOWER": {"IN": ["nota", "recordatorio"]}}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "activa"}, {"LOWER": "modo"}, {"LOWER": "interrumpir"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["haz", "hacé"]}}, {"LOWER": "chequeo"}, {"LOWER": "médico"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "avísame"}, {"LOWER": "si"}, {"LOWER": "hay"}, {"LOWER": "consumos"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["pon", "poné"]}}, {"LOWER": "alarma"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["enciende", "prende"]}}, {"LOWER": "el"}, {"LOWER": "ventilador"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["sube", "baja"]}}, {"LOWER": "la"}, {"LOWER": "temperatura"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["enciende", "apaga"]}}, {"LOWER": "la"}, {"LOWER": "calefacción"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["sube", "baja"]}}, {"LOWER": "el"}, {"LOWER": "brillo"}]},

    # Comandos e intenciones (más variantes y flexibilidad)
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["enciende", "prende"]}}, {"LOWER": {"IN": ["la", "las"]}}, {"LOWER": {"IN": ["luz", "luces"]}}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["apaga", "apagá"]}}, {"LOWER": {"IN": ["la", "las"]}}, {"LOWER": {"IN": ["tele", "televisor", "luz", "luces"]}}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["sube", "subí"]}}, {"LOWER": "el"}, {"LOWER": "volumen"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["baja", "bajá"]}}, {"LOWER": {"IN": ["la", "el"]}}, {"LOWER": {"IN": ["música", "volumen"]}}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["abre", "abrí"]}}, {"LOWER": "la"}, {"LOWER": "puerta"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["pon", "poné"]}}, {"LOWER": "música"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["reserva", "reservá"]}}, {"LOWER": "auto"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["crea", "creá"]}}, {"LOWER": "nota"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "qué"}, {"LOWER": "clima"}, {"LOWER": "hace"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "busca"}, {"LOWER": "noticias"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "llama"}, {"LOWER": "a"}, {"ENT_TYPE": "PERSON"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "imprime"}, {"LOWER": "modelo"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "analiza"}, {"LOWER": "modelo"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "guarda"}, {"LOWER": "nota"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "activa"}, {"LOWER": "modo"}, {"LOWER": "interrumpir"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["haz", "hacé"]}}, {"LOWER": "chequeo"}, {"LOWER": "médico"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "avísame"}, {"LOWER": "si"}, {"LOWER": "hay"}, {"LOWER": "consumos"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["pon", "poné"]}}, {"LOWER": "alarma"}]},
]
