# Lista de patrones personalizados para EntityRuler (formato Python)
patterns = [
        # Patrones para detectar solo el dispositivo en cualquier contexto
        {"label": "DISPOSITIVO", "pattern": [{"LOWER": "luces"}]},
        {"label": "DISPOSITIVO", "pattern": [{"LOWER": "luz"}]},
        {"label": "DISPOSITIVO", "pattern": [{"LOWER": "tele"}]},
        {"label": "DISPOSITIVO", "pattern": [{"LOWER": "televisor"}]},
        {"label": "DISPOSITIVO", "pattern": [{"LOWER": "puerta"}]},
        {"label": "DISPOSITIVO", "pattern": [{"LOWER": "ventana"}]},
        {"label": "DISPOSITIVO", "pattern": [{"LOWER": "impresora"}]},
        {"label": "DISPOSITIVO", "pattern": [{"LOWER": "impresora"}, {"LOWER": "3d"}]},
        {"label": "DISPOSITIVO", "pattern": [{"LOWER": "cámara"}]},
        {"label": "DISPOSITIVO", "pattern": [{"LOWER": "auto"}]},
        {"label": "DISPOSITIVO", "pattern": [{"LOWER": "música"}]},
        {"label": "DISPOSITIVO", "pattern": [{"LOWER": "notas"}]},
        {"label": "DISPOSITIVO", "pattern": [{"LOWER": "clima"}]},
        {"label": "DISPOSITIVO", "pattern": [{"LOWER": "noticias"}]},
        {"label": "DISPOSITIVO", "pattern": [{"LOWER": "contactos"}]},
        {"label": "DISPOSITIVO", "pattern": [{"LOWER": "modelo"}, {"LOWER": "3d"}]},
        {"label": "DISPOSITIVO", "pattern": [{"LOWER": "sistema"}, {"LOWER": "de"}, {"LOWER": "seguridad"}]},
    # Dispositivos y variantes
    {"label": "DISPOSITIVO", "pattern": "televisor"},
    {"label": "DISPOSITIVO", "pattern": "tele"},
    {"label": "DISPOSITIVO", "pattern": "luz"},
    {"label": "DISPOSITIVO", "pattern": "luces"},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": "la"}, {"LOWER": "luz"}]},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": "las"}, {"LOWER": "luces"}]},
    {"label": "DISPOSITIVO", "pattern": "volumen"},
    {"label": "DISPOSITIVO", "pattern": "puerta"},
    {"label": "DISPOSITIVO", "pattern": [{"LOWER": "puerta"}, {"LOWER": "principal"}]},
    {"label": "DISPOSITIVO", "pattern": "ventana"},
    {"label": "DISPOSITIVO", "pattern": "impresora 3D"},
    {"label": "DISPOSITIVO", "pattern": "cámara"},
    {"label": "DISPOSITIVO", "pattern": "auto"},
    {"label": "DISPOSITIVO", "pattern": "música"},
    {"label": "DISPOSITIVO", "pattern": "notas"},
    {"label": "DISPOSITIVO", "pattern": "clima"},
    {"label": "DISPOSITIVO", "pattern": "noticias"},
    {"label": "DISPOSITIVO", "pattern": "contactos"},
    {"label": "DISPOSITIVO", "pattern": "modelo 3D"},
    {"label": "DISPOSITIVO", "pattern": "sistema de seguridad"},

    # Comandos e intenciones (más variantes y flexibilidad)
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["enciende", "prende"]}}, {"LOWER": {"IN": ["la", "las"]}}, {"LOWER": {"IN": ["luz", "luces"]}}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["apaga", "apagá"]}}, {"LOWER": {"IN": ["la", "las"]}}, {"LOWER": {"IN": ["tele", "televisor", "luz", "luces"]}}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["sube", "subí"]}}, {"LOWER": "el"}, {"LOWER": "volumen"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["baja", "bajá"]}}, {"LOWER": {"IN": ["la", "el"]}}, {"LOWER": {"IN": ["música", "volumen"]}}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["abre", "abrí"]}}, {"LOWER": "la"}, {"LOWER": "puerta"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["pon", "poné"]}}, {"LOWER": "música"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["reserva", "reservá"]}}, {"LOWER": "auto"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["crea", "creá"]}}, {"LOWER": "nota"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "qué"}, {"LOWER": "clima"}, {"LOWER": "hace"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "busca"}, {"LOWER": "noticias"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "llama"}, {"LOWER": "a"}, {"ENT_TYPE": "PERSON"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "imprime"}, {"LOWER": "modelo"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "analiza"}, {"LOWER": "modelo"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "guarda"}, {"LOWER": "nota"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "activa"}, {"LOWER": "modo"}, {"LOWER": "interrumpir"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["haz", "hacé"]}}, {"LOWER": "chequeo"}, {"LOWER": "médico"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": "avísame"}, {"LOWER": "si"}, {"LOWER": "hay"}, {"LOWER": "consumos"}]},
    {"label": "COMANDO", "pattern": [{"LOWER": {"IN": ["pon", "poné"]}}, {"LOWER": "alarma"}]},
]
